title: "Abdul Rahman"
email: abdulrahman.ashraf4528@gmail.com
description: AI Engineer · Deep Learning · Vision-Language Models · Computer Vision
baseurl: ""
url: "https://abdulrahman45284528.github.io"
theme: minima

header_pages:
  - index.md
