title: "Abdul Rahman"
description: AI Engineer · Deep Learning · Vision-Language Models · Computer Vision
email: abdulrahman.ashraf@gmail.com
github_username: abdulrahman45284528
linkedin_username: your-linkedin-id
remote_theme: b2a3e8/jekyll-theme-console

plugins:
  - jekyll-remote-theme
